<?php

namespace Hackle\Common;

use Hackle\Internal\Lang\Enum;

/**
 * @method static SDK_NOT_READY()
 * @method static EXCEPTION()
 * @method static INVALID_INPUT()
 * @method static EXPERIMENT_NOT_FOUND()
 * @method static EXPERIMENT_DRAFT()
 * @method static EXPERIMENT_PAUSED()
 * @method static EXPERIMENT_COMPLETED()
 * @method static OVERRIDDEN()
 * @method static TRAFFIC_NOT_ALLOCATED()
 * @method static NOT_IN_MUTUAL_EXCLUSION_EXPERIMENT()
 * @method static IDENTIFIER_NOT_FOUND()
 * @method static VARIATION_DROPPED()
 * @method static TRAFFIC_ALLOCATED()
 * @method static TRAFFIC_ALLOCATED_BY_TARGETING()
 * @method static NOT_IN_EXPERIMENT_TARGET()
 * @method static FEATURE_FLAG_NOT_FOUND()
 * @method static FEATURE_FLAG_INACTIVE()
 * @method static INDIVIDUAL_TARGET_MATCH()
 * @method static TARGET_RULE_MATCH()
 * @method static DEFAULT_RULE()
 * @method static REMOTE_CONFIG_PARAMETER_NOT_FOUND()
 * @method static TYPE_MISMATCH()
 */
class DecisionReason extends Enum
{
    const SDK_NOT_READY = "SDK_NOT_READY";
    const EXCEPTION = "EXCEPTION";
    const INVALID_INPUT = "INVALID_INPUT";
    const EXPERIMENT_NOT_FOUND = "EXPERIMENT_NOT_FOUND";
    const EXPERIMENT_DRAFT = "EXPERIMENT_DRAFT";
    const EXPERIMENT_PAUSED = "EXPERIMENT_PAUSED";
    const EXPERIMENT_COMPLETED = "EXPERIMENT_COMPLETED";
    const OVERRIDDEN = "OVERRIDDEN";
    const TRAFFIC_NOT_ALLOCATED = "TRAFFIC_NOT_ALLOCATED";
    const NOT_IN_MUTUAL_EXCLUSION_EXPERIMENT = "NOT_IN_MUTUAL_EXCLUSION_EXPERIMENT";
    const IDENTIFIER_NOT_FOUND = "IDENTIFIER_NOT_FOUND";
    const VARIATION_DROPPED = "VARIATION_DROPPED";
    const TRAFFIC_ALLOCATED = "TRAFFIC_ALLOCATED";
    const TRAFFIC_ALLOCATED_BY_TARGETING = "TRAFFIC_ALLOCATED_BY_TARGETING";
    const NOT_IN_EXPERIMENT_TARGET = "NOT_IN_EXPERIMENT_TARGET";
    const FEATURE_FLAG_NOT_FOUND = "FEATURE_FLAG_NOT_FOUND";
    const FEATURE_FLAG_INACTIVE = "FEATURE_FLAG_INACTIVE";
    const INDIVIDUAL_TARGET_MATCH = "INDIVIDUAL_TARGET_MATCH";
    const TARGET_RULE_MATCH = "TARGET_RULE_MATCH";
    const DEFAULT_RULE = "DEFAULT_RULE";
    const REMOTE_CONFIG_PARAMETER_NOT_FOUND = "REMOTE_CONFIG_PARAMETER_NOT_FOUND";
    const TYPE_MISMATCH = "TYPE_MISMATCH";
}
