name: Test

on:
  pull_request:

jobs:
  php-sdk-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 7.1
      - name: Test
        uses: php-actions/phpunit@v3
        with:
          version: 7.5.20
          bootstrap: vendor/autoload.php
          configuration: test/phpunit.xml
          args: --coverage-text
          php_version: 7.1